version: "3.8"
services:
  frontend:
    build: ./frontend
    image: amitpurohit29/todo-app-frontend:latest
    container_name: todo-app-frontend
    ports:
    - target: 5000
      published: 80
  
  backend:
    build: ./backend
    image: amitpurohit29/todo-app-backend:latest
    container_name: todo-app-backend
    environment:
      DATABASE_URI:
    ports:
    - target: 5000
      published: 5000
    